blank_issues_enabled: false
contact_links:
  - name: Let's have a good discussion!
    url: https://github.com/2moe/tmoe-linux/discussions
    about: "(o゜▽゜)o☆ You can use čeština, Deutsch, español, français, язы́к & português, etc."
